export const maps = {
    title: {
      backend: 'Backend Engineer',
      frontend: 'Frontend Engineer',
      ai_automation: 'AI & Automation Engineer',
      crm: 'CRM Developer',
      data_analytics: 'Data Analytics',
      data_engineer: 'Data Engineer',
      data_scientist: 'Data Scientist',
      devops_sre_platform: 'DevOps / SRE / Platform',
      embedded: 'Embedded Systems Engineer',
      engineering_manager: 'Engineering Manager',
      executive: 'Executive (C-level, director, etc.)',
      fullstack: 'Full-stack Engineer',
      hardware: 'Hardware Engineer (Semiconductors, Digital Design, Electronics, etc)',
      mobile: 'Mobile Development Engineer',
      product_manager: 'Product Manager',
      product_owner: 'Product Owner',
      testing: 'QA / SDET Engineer',
      research: 'R&D Engineer (Computer Vision, NLP, etc.)',
      scrum: 'Scrum Master',
      security: 'Security/Network Engineer',
      system_arch: 'Systems Architect',
      technical_support: 'Technical Support',
      ui_ux: 'UI/UX Designer/Engineer',
    },
    level: {
      c_level: 'C-Level',
      director: 'Director',
      group_product_manager: 'Group Product Manager',
      intern: 'Intern',
      junior: 'Junior',
      manager: 'Manager',
      mid_level: 'Mid-level',
      principal: 'Principal',
      senior: 'Senior',
      senior_manager: 'Senior Manager',
      senior_principal: 'Senior Principal',
      senior_staff: 'Senior Staff',
      staff: 'Staff',
      team_lead: 'Team Lead',
      vp: 'VP',
    },
    gender: {
      male: 'Male',
      female: 'Female',
    },
    degree: {
      yes: 'Yes',
      no: 'No',
    },
    businessMarket: {
      global: 'Global',
      regional: 'Regional',
      local: 'Local',
    },
    businessSize: {
      large: 'A Large Enterprise/Multinational Company',
      medium: 'A Small and Medium Enterprise',
      small: 'A Start-up',
    },
    businessFocus: {
      product: 'Product-based company',
      software_house: 'Software House',
    },
    businessLine: {
      b2b: 'B2B',
      b2c: 'B2C',
      both: 'B2B & B2C lines',
    },
    programmingLanguage: {
      java_script: 'JavaScript',
      type_script: 'TypeScript',
      python: 'Python',
      c_sharp: 'C#',
      java: 'JPava',
      php: 'PHP',
      c_cplusplus: 'C/C++',
      kotlin: 'Kotlin',
      swift: 'Swift',
      dart: 'Dart',
      go: 'Go',
      r: 'R',
      scala: 'Scala',
      rust: 'Rust',
    },
  };
  